import localFont from "next/font/local";
import "./globals.css";

const myFont = localFont({
  src: "./font/Product-Sans-Regular.ttf",
  display: "swap",
});

const myFontRegular = localFont({
  src: "./font/Product-Sans-Regular.ttf",
  display: "swap",
});

const myFontBold = localFont({
  src: "./font/Product-Sans-Bold.ttf",
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${myFont.className} ${myFontBold.className}`}>
        {children}
      </body>
    </html>
  );
}
